# Generated by Django 3.2.7 on 2021-09-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('post_title', models.CharField(max_length=240)),
                ('content', models.CharField(max_length=240)),
            ],
        ),
    ]
